[project]
name = "uz-tickets"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.22.0",
    "httpx[http2]>=0.28.1",
    "playwright>=1.52.0",
    "playwright-stealth>=2.0.0",
]
